version: '3.7'

services:
  test:
    image: node:14-alpine
    user: '1000'
    command: yarn test
    environment:
      DB_TYPE: postgres
      DB_HOST: test_postgres
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: test
      DB_DATABASE: nestjs-testing
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - test_postgres

  test_postgres:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test
      POSTGRES_DB: nestjs-testing